# Generated by Django 4.0 on 2023-02-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polling", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
